=== 10MG/sqltool/src/main/java/cn/tenmg/sqltool/config/sqltool.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.10mg.cn/schema/sqltool"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.10mg.cn/schema/sqltool"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
	<xsd:element name="sqltool">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="dsql" maxOccurs="unbounded"
					minOccurs="0" type="dsqlType">
					<xsd:annotation>
						<xsd:documentation><![CDATA[动态结构化查询语言（DSQL）配置]]></xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="dsqlType">
		<xsd:sequence>
			<xsd:element name="filter" maxOccurs="1" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation><![CDATA[参数过滤器配置]]></xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="blank" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[空白字符串参数过滤器配置]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:attribute name="params" type="xsd:string"
									default="*">
									<xsd:annotation>
										<xsd:documentation><![CDATA[参数列表，使用逗号分隔。默认*，代表全部]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="eq" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[等值参数过滤器配置]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:attribute name="params" type="xsd:string"
									default="*">
									<xsd:annotation>
										<xsd:documentation><![CDATA[参数列表，使用逗号分隔。默认*，代表全部]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>

								<xsd:attribute name="value" type="xsd:string"
									use="required">
									<xsd:annotation>
										<xsd:documentation><![CDATA[供比较的值]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="converter" maxOccurs="1" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation><![CDATA[参数转换器配置]]></xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="to-number" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[参数数字类型转换器配置模型]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:attribute name="params" type="xsd:string"
									use="required">
									<xsd:annotation>
										<xsd:documentation><![CDATA[参数列表，使用逗号分隔]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>

								<xsd:attribute name="formatter" type="xsd:string">
									<xsd:annotation>
										<xsd:documentation><![CDATA[格式化模板]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="to-date" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[参数日期类型转换器配置模型]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:attribute name="params" type="xsd:string"
									use="required">
									<xsd:annotation>
										<xsd:documentation><![CDATA[参数列表，使用逗号分隔]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>

								<xsd:attribute name="formatter" type="xsd:string"
									default="yyyy-MM-dd">
									<xsd:annotation>
										<xsd:documentation><![CDATA[格式化模板（默认值yyyy-MM-dd）]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>

						<xsd:element name="wrap-string" maxOccurs="unbounded"
							minOccurs="0">
							<xsd:annotation>
								<xsd:documentation><![CDATA[字符串参数包装转换器配置模型]]></xsd:documentation>
							</xsd:annotation>
							<xsd:complexType>
								<xsd:attribute name="params" type="xsd:string"
									use="required">
									<xsd:annotation>
										<xsd:documentation><![CDATA[参数列表，使用逗号分隔]]></xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>

								<xsd:attribute name="formatter"
									default="%${value}%">
									<xsd:annotation>
										<xsd:documentation><![CDATA[包装模板（默认值%${value}%）]]></xsd:documentation>
									</xsd:annotation>
									<xsd:simpleType>
										<xsd:union memberTypes="normalLikes xsd:string"></xsd:union>
									</xsd:simpleType>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="script" maxOccurs="1"
				type="xsd:string" minOccurs="1">
				<xsd:annotation>
					<xsd:documentation><![CDATA[动态结构化查询语言（DSQL）脚本]]></xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string"
			use="required">
			<xsd:annotation>
				<xsd:documentation><![CDATA[动态结构化查询语言（DSQL）编号]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<!-- 类型定义 -->
	<xsd:simpleType name="normalLikes">
		<xsd:annotation>
			<xsd:documentation><![CDATA[常用LIKE参数包装枚举]]></xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="%${value}%"></xsd:enumeration>
			<xsd:enumeration value="%${value}"></xsd:enumeration>
			<xsd:enumeration value="${value}%"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== 10MG/sqltool/src/test/resources/dsql/sqlserver.dsql.xml
<?xml version="1.0" encoding="utf-8"?>
<sqltool xmlns="http://www.10mg.cn/schema/sqltool"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.10mg.cn/schema/sqltool http://www.10mg.cn/schema/sqltool.xsd">
	<dsql id="sqlserver_offset_fetch">	
		<converter>
			<wrap-string params="staffName" formatter="%${value}%" />
		</converter>
		<script>
			<![CDATA[
				SELECT
				  staff_id,
				  staff_name
				FROM STAFF_INFO
				WHERE STAFF_NAME LIKE :staffName
				ORDER BY STAFF_NAME
				OFFSET 0 ROW FETCH NEXT :offset ROW ONLY
			]]>
		</script>
	</dsql>
	
	<dsql id="sqlserver_offset">
		<converter>
			<wrap-string params="staffName" formatter="%${value}%" />
		</converter>
		<script>
			<![CDATA[
				SELECT
				  staff_id,
				  staff_name
				FROM STAFF_INFO
				WHERE STAFF_NAME LIKE :staffName
				ORDER BY STAFF_NAME
				OFFSET 10 ROW
			]]>
		</script>
	</dsql>
</sqltool>
